#!/usr/bin/env bash
# Write a boxes.sh manifest listing every GitHub repo the gh login can see.
#
#   scripts/list-repos.sh [out-file]        # default: local/boxes.manifest
#
# The result is a menu, not a plan: every line starts commented out, except
# boxes that already exist, so feeding it to boxes.sh straight away creates
# nothing new. Uncomment the repos you want, and put several repos on one
# line to make them a single box.
#
# local/ is gitignored. The list names real orgs and repos, which this repo
# never commits; examples/boxes.manifest shows the format.
#
# Never overwrites an existing manifest, since that would throw away your
# selections. If the file exists, the fresh list goes to <out-file>.new so you
# can diff the two.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
OUT="${1:-$ROOT/local/boxes.manifest}"

command -v gh >/dev/null || { echo "gh is required."; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "gh is not logged in; run: gh auth login"; exit 1; }

mkdir -p "$(dirname "$OUT")"
[[ -e "$OUT" ]] && { echo "$OUT exists; writing $OUT.new instead (diff them, then merge by hand)."; OUT="$OUT.new"; }

# owner, collaborator and org-member repos -- everything the token can clone.
# TSV: full_name  private  archived  fork  pushed_at
repos=$(gh api --paginate 'user/repos?per_page=100&affiliation=owner,collaborator,organization_member' \
  -q '.[] | [.full_name, .private, .archived, .fork, (.pushed_at // "")[0:10]] | @tsv' | sort -f)

# Boxes that already exist stay uncommented, so the manifest matches reality.
existing=$(pixels list 2>/dev/null | awk 'NR>1 {print $1}' || true)

# Box names: lowercase, digits, dashes (they become px-<name> and a herdr
# workspace). A repo name shared by two owners gets the owner prefixed in
# both places.
name_of() { tr '[:upper:]' '[:lower:]' <<<"$1" | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'; }
dupes=$(cut -f1 <<<"$repos" | awk -F/ '{print tolower($2)}' | sort | uniq -d)

{
  echo "# Boxes manifest for boxes.sh -- generated by list-repos.sh on $(date +%F)"
  echo "# from the $(wc -l <<<"$repos") repos the gh login can access. Local only; do not commit."
  echo "#"
  echo "# Uncomment a line to give that repo a box, then:"
  echo "#   scripts/boxes.sh $(realpath --relative-to="$ROOT" "$OUT" 2>/dev/null || echo "$OUT") [--dry-run]"
  echo "# Put several repos on one line to share one box. Lines already uncommented"
  echo "# are boxes that exist. Format and options: examples/boxes.manifest."
  owner=""
  while IFS=$'\t' read -r full private archived fork pushed; do
    o="${full%%/*}"; r="${full#*/}"
    if [[ "$o" != "$owner" ]]; then
      owner="$o"
      echo; echo "# ---- $owner ($(cut -f1 <<<"$repos" | grep -c "^$owner/"))"
    fi
    name=$(name_of "$r")
    grep -qx "$(tr '[:upper:]' '[:lower:]' <<<"$r")" <<<"$dupes" && name=$(name_of "$o-$r")
    tags=()
    [[ "$private" == true ]] && tags+=(private) || tags+=(public)
    [[ "$archived" == true ]] && tags+=(archived)
    [[ "$fork" == true ]] && tags+=(fork)
    [[ -n "$pushed" ]] && tags+=("pushed $pushed")
    prefix="# "; grep -qx "$name" <<<"$existing" && prefix=""
    printf '%s%-28s %-44s # %s\n' "$prefix" "$name" "$full" "$(IFS=,; echo "${tags[*]}" | sed 's/,/, /g')"
  done <<<"$repos"
} > "$OUT"

echo "Wrote $OUT ($(wc -l <<<"$repos") repos)."
